/**
 * Curated show-boat data layer. Source of truth: data/show-boats.json,
 * generated by scripts/import-show-boats.mjs from Giselle's "2026 Feature
 * Boats" workbook (see scripts/parse-feature-boats.ps1). The daily
 * "vbs-feature-boats-daily-check" scheduled task keeps it in sync.
 *
 * These are the dealers' selected feature boats for the show — a curated
 * lineup, not a live inventory feed. No prices by design (client brand
 * review): pricing conversations happen with the dealer at the show.
 */
import raw from "@/data/show-boats.json";

export type DealerRef = { name: string; loc: string; phone: string };

export type ShowBoat = {
  slug: string;
  brand: string;
  model: string;
  year: number | null;
  /** 1 = dealer's hero boat, 2 = supporting feature. */
  priority: number;
  /** Dealer-supplied note, e.g. "NJ Boat Show Debut". */
  notes: string;
  /** Shared manufacturer showcase (no single-dealer listing page). */
  shared: boolean;
  sourceUrl: string | null;
  brandUrl: string | null;
  dealers: DealerRef[];
  photos: string[];
  blurb: string;
  lengthFt: number | null;
};

export type WaitingDealer = { dealer: string; brands: string[] };

type ShowData = {
  generatedAt: string;
  boatCount: number;
  boats: ShowBoat[];
  waiting: WaitingDealer[];
};

const data = raw as unknown as ShowData;

export const showBoats: ShowBoat[] = data.boats;
export const waitingDealers: WaitingDealer[] = data.waiting;
export const generatedAt: string = data.generatedAt;

export const boatBySlug = (slug: string): ShowBoat | undefined =>
  showBoats.find((b) => b.slug === slug);

export const boatTitle = (b: ShowBoat): string =>
  [b.year ?? "", b.brand, b.model].filter(Boolean).join(" ");

export const allBrands = (): string[] =>
  [...new Set(showBoats.map((b) => b.brand))].sort();

export const allDealers = (): string[] =>
  [...new Set(showBoats.flatMap((b) => b.dealers.map((d) => d.name)))].sort();

/**
 * Fair featured rotation: every page load picks `count` DEALERS at random,
 * then one random photo-bearing boat from each — so every dealer gets equal
 * access to the featured real estate regardless of how many boats they
 * brought. Call from useEffect/useMemo on the client so each load reshuffles.
 */
export function pickFeatured(count = 6): ShowBoat[] {
  const withPhotos = showBoats.filter((b) => b.photos.length > 0);
  const byDealer = new Map<string, ShowBoat[]>();
  for (const b of withPhotos) {
    for (const d of b.dealers) {
      const list = byDealer.get(d.name) ?? [];
      list.push(b);
      byDealer.set(d.name, list);
    }
  }
  const dealerNames = [...byDealer.keys()];
  for (let i = dealerNames.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [dealerNames[i], dealerNames[j]] = [dealerNames[j], dealerNames[i]];
  }
  const picked: ShowBoat[] = [];
  const seen = new Set<string>();
  for (const name of dealerNames) {
    if (picked.length >= count) break;
    const pool = byDealer.get(name)!.filter((b) => !seen.has(b.slug));
    if (!pool.length) continue;
    const b = pool[Math.floor(Math.random() * pool.length)];
    seen.add(b.slug);
    picked.push(b);
  }
  return picked;
}
